# Generated by Django 3.2.16 on 2022-12-31 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
        ('store', '0014_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Cash on delivery', 'Cash on delivery'), ('Bkash', 'Bkash')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.shipingaddress'),
        ),
    ]
